// Package engine is the core of the SublimeGo framework.
//
// It provides the main application engine that orchestrates all components
// including routing, middleware, resource management, and template rendering.
// The engine follows a resource-oriented architecture inspired by Laravel Filament.
//
// Features:
//   - HTTP server with standard library
//   - Resource registration and discovery
//   - Custom pages support (like Filament)
//   - Automatic CLI generation (make:resource, make:page)
//   - Middleware stack management
//   - Template rendering with Templ
//   - Authentication handlers
//   - Panel configuration
//
// Basic usage:
//
//	panel := engine.NewPanel("admin").
//		SetDatabase(db).
//		SetAuthManager(authManager).
//		AddResources(&UserResource{}, &ProductResource{}).
//		AddPages(settingsPage, reportsPage)
//
//	http.ListenAndServe(":8080", panel.Router())
//
// CLI Generation:
//
// Resources and pages can be generated automatically via CLI:
//
//	# Generate a new resource with CRUD
//	sublimego make:resource Product
//
//	# Generate a custom page
//	sublimego make:page Settings --group=System --icon=settings
//
//	# Scan and register all resources/pages
//	sublimego scan
//
// Custom Pages:
//
// Pages are standalone views that don't follow the CRUD pattern.
// Use them for settings, reports, analytics, or any custom content.
// Pages can include forms, tables, and any UI components.
//
//	settingsPage := engine.NewSimplePage("settings", "Settings", func(ctx context.Context, r *http.Request) templ.Component {
//		// You can use form builder
//		form := form.New().SetSchema(
//			form.Text("site_name").Label("Site Name").Required(),
//			form.Email("admin_email").Label("Admin Email"),
//		)
//		// You can use table builder
//		table := table.New(data).WithColumns(
//			table.Text("key").Label("Setting"),
//			table.Text("value").Label("Value"),
//		)
//		return views.SettingsPage(form, table)
//	}).WithIcon("settings").WithGroup("System")
//
//	panel.AddPages(settingsPage)
//
// Page Structure (generated by CLI):
//
//	internal/pages/
//	├── settings/
//	│   ├── page.go         # Page logic with form/table builders
//	│   └── content.templ   # Templ template for rendering
//	└── reports/
//	    ├── page.go
//	    └── content.templ
package engine
